export const TOP_50_INDIAN_CARDS = [
    "HDFC Infinia Metal Edition",
    "HDFC Diners Club Black",
    "HDFC Regalia Gold",
    "HDFC Millennia",
    "Swiggy HDFC Bank",
    "Tata Neu Infinity HDFC",
    "SBI Cashback Card",
    "SBI Card PRIME",
    "SBI Card ELITE",
    "SimplyCLICK SBI Card",
    "BPCL SBI Card OCTANE",
    "Axis Bank Magnus",
    "Axis Bank Atlas",
    "Axis Bank Reserve",
    "Flipkart Axis Bank",
    "Axis Bank Ace",
    "Axis Bank Vistara Infinite",
    "Amazon Pay ICICI Bank",
    "ICICI Emeralde",
    "ICICI Sapphiro",
    "ICICI Rubyx",
    "MakeMyTrip ICICI Bank Signature",
    "American Express Platinum Travel",
    "American Express Platinum Charge",
    "American Express Gold",
    "American Express SmartEarn",
    "American Express MRCC",
    "IndusInd Bank Pinnacle",
    "IndusInd Bank Legend",
    "IndusInd Bank Tiger",
    "EazyDiner IndusInd Bank",
    "Standard Chartered Ultimate",
    "Standard Chartered Smart",
    "IDFC FIRST Wealth",
    "IDFC FIRST Select",
    "IDFC FIRST Classic",
    "AU Small Finance Bank Zenith",
    "AU Small Finance Bank Vetta",
    "AU Small Finance Bank LIT",
    "Yes Private Prime",
    "Yes First Preferred",
    "RBL Bank World Safari",
    "RBL Bank Icon",
    "OneCard",
    "Kotak White Card",
    "Kotak Zen",
    "Kotak League",
    "HSBC Cashback",
    "Citi PremierMiles",
    "Tata Neu Plus HDFC"
];
