-- Create system settings table for dynamic AI configurations
CREATE TABLE public.system_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_by UUID REFERENCES public.admin_users(id)
);

-- Enable RLS (Read for everyone if needed, but only Admin writes)
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Settings are viewable by everyone." ON public.system_settings FOR SELECT USING (true);
CREATE POLICY "Settings can be inserted by admins." ON public.system_settings FOR INSERT WITH CHECK (auth.uid() IN (SELECT id FROM public.admin_users));
CREATE POLICY "Settings can be updated by admins." ON public.system_settings FOR UPDATE USING (auth.uid() IN (SELECT id FROM public.admin_users));

-- Create the Event Queue table for scraper payloads
CREATE TABLE public.ingestion_queue (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    source_url TEXT NOT NULL,
    bank_name TEXT,
    raw_payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PROCESSING', 'MAPPED_AWAITING_REVIEW', 'COMPLETED', 'ERROR')),
    mapped_card_data JSONB, -- The structural representation generated by the AI
    error_log TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE public.ingestion_queue ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins have full access to queue" ON public.ingestion_queue FOR ALL USING (auth.uid() IN (SELECT id FROM public.admin_users));
-- We allow an authenticated service role to insert (from our Cron)

-- Create Audit Log table for BFSI compliance
CREATE TABLE public.card_audit_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    card_id UUID REFERENCES public.cards(id) ON DELETE CASCADE,
    changed_by UUID REFERENCES public.admin_users(id),
    action TEXT NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'DELETE', 'APPROVE_INGESTION')),
    old_data JSONB,
    new_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.card_audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins have reading access to audit logs" ON public.card_audit_logs FOR SELECT USING (auth.uid() IN (SELECT id FROM public.admin_users));
CREATE POLICY "Admins have insert access to audit logs" ON public.card_audit_logs FOR INSERT WITH CHECK (auth.uid() IN (SELECT id FROM public.admin_users));

-- Insert Default AI Setup (Allows admin to change key later)
INSERT INTO public.system_settings (key, value)
VALUES (
    'ai_processor_config', 
    '{"provider": "openai", "model": "gpt-4o-mini", "api_key": "", "base_url": "https://api.openai.com/v1"}'::jsonb
);
